## This configuration was generated by terraform-provider-oci

resource oci_artifacts_container_configuration export_container_configuration {
  compartment_id                      = "ocid1.compartment.oc1..aaaaaaaa5273iaty2alko6dbl5362c7q4mwcsnflp2drrauewl5evt4qol3q"
  is_repository_created_on_first_push = "true"
}

