## This configuration was generated by terraform-provider-oci

data oci_identity_availability_domain export_fttO-AP-CHUNCHEON-1-AD-1 {
  compartment_id = oci_artifacts_container_configuration.export_container_configuration.id
  ad_number      = "1"
}
