## This configuration was generated by terraform-provider-oci

resource oci_containerengine_cluster export_cluster1 {
  cluster_pod_network_options {
    cni_type = "OCI_VCN_IP_NATIVE"
  }
  compartment_id = oci_artifacts_container_configuration.export_container_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/jungin.hong@oracle.com"
    "Oracle-Tags.CreatedOn" = "2026-02-02T05:24:49.524Z"
  }
  endpoint_config {
    is_public_ip_enabled = "true"
    nsg_ids = [
    ]
    subnet_id = oci_core_subnet.export_oke-k8sApiEndpoint-subnet-quick-cluster1-c388f9bef-regional.id
  }
  freeform_tags = {
    "OKEclusterName" = "cluster1"
  }
  image_policy_config {
    is_policy_enabled = "false"
  }
  #kms_key_id = <<Optional value not found in discovery>>
  kubernetes_version = "v1.34.1"
  name               = "cluster1"
  options {
    add_ons {
      is_kubernetes_dashboard_enabled = "false"
      is_tiller_enabled               = "false"
    }
    admission_controller_options {
      is_pod_security_policy_enabled = "false"
    }
    ip_families = [
      "IPv4",
    ]
    kubernetes_network_config {
      pods_cidr     = "10.244.0.0/16"
      services_cidr = "10.96.0.0/16"
    }
    #open_id_connect_discovery = <<Optional value not found in discovery>>
    #open_id_connect_token_authentication_config = <<Optional value not found in discovery>>
    persistent_volume_config {
      defined_tags = {
      }
      freeform_tags = {
        "OKEclusterName" = "cluster1"
      }
    }
    service_lb_config {
      backend_nsg_ids = [
      ]
      defined_tags = {
      }
      freeform_tags = {
        "OKEclusterName" = "cluster1"
      }
    }
    service_lb_subnet_ids = [
      oci_core_subnet.export_oke-svclbsubnet-quick-cluster1-c388f9bef-regional.id,
    ]
  }
  type   = "ENHANCED_CLUSTER"
  vcn_id = oci_core_vcn.export_oke-vcn-quick-cluster1-c388f9bef.id
}

resource oci_containerengine_addon export_cluster1_addon {
  addon_name = "CoreDNS"
  cluster_id = oci_containerengine_cluster.export_cluster1.id
  #override_existing = <<Optional value not found in discovery>>
  remove_addon_resources_on_delete = "true"
  #version = <<Optional value not found in discovery>>
}

resource oci_containerengine_addon export_cluster1_addon_1 {
  addon_name = "KubeProxy"
  cluster_id = oci_containerengine_cluster.export_cluster1.id
  #override_existing = <<Optional value not found in discovery>>
  remove_addon_resources_on_delete = "true"
  #version = <<Optional value not found in discovery>>
}

resource oci_containerengine_addon export_cluster1_addon_2 {
  addon_name = "NvidiaGpuPlugin"
  cluster_id = oci_containerengine_cluster.export_cluster1.id
  #override_existing = <<Optional value not found in discovery>>
  remove_addon_resources_on_delete = "true"
  #version = <<Optional value not found in discovery>>
}

resource oci_containerengine_addon export_cluster1_addon_3 {
  addon_name = "OciVcnIpNative"
  cluster_id = oci_containerengine_cluster.export_cluster1.id
  #override_existing = <<Optional value not found in discovery>>
  remove_addon_resources_on_delete = "true"
  #version = <<Optional value not found in discovery>>
}

