## This configuration was generated by terraform-provider-oci

resource oci_core_nat_gateway export_oke-ngw-quick-cluster1-c388f9bef {
  block_traffic  = "false"
  compartment_id = oci_artifacts_container_configuration.export_container_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/jungin.hong@oracle.com"
    "Oracle-Tags.CreatedOn" = "2026-02-02T05:24:48.016Z"
  }
  display_name = "oke-ngw-quick-cluster1-c388f9bef"
  freeform_tags = {
  }
  public_ip_id = "ocid1.publicip.oc1.ap-chuncheon-1.aaaaaaaa7bdixuklkugbmvubspjf4czczxsad2qddu5xcmrntyicmpmyytna"
  #route_table_id = <<Optional value not found in discovery>>
  vcn_id = oci_core_vcn.export_oke-vcn-quick-cluster1-c388f9bef.id
}

resource oci_core_nat_gateway export_test-nat {
  block_traffic  = "false"
  compartment_id = oci_artifacts_container_configuration.export_container_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/jungin.hong@oracle.com"
    "Oracle-Tags.CreatedOn" = "2026-01-30T05:05:57.681Z"
  }
  display_name = "test-nat"
  freeform_tags = {
  }
  public_ip_id = "ocid1.publicip.oc1.ap-chuncheon-1.aaaaaaaalb3nns2wpengeclmmnapn25qczh2g2xh2djdwiavo6zbz4tuippq"
  #route_table_id = <<Optional value not found in discovery>>
  vcn_id = oci_core_vcn.export_terraform-test-vcn.id
}

resource oci_core_internet_gateway export_oke-igw-quick-cluster1-c388f9bef {
  compartment_id = oci_artifacts_container_configuration.export_container_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/jungin.hong@oracle.com"
    "Oracle-Tags.CreatedOn" = "2026-02-02T05:24:47.890Z"
  }
  display_name = "oke-igw-quick-cluster1-c388f9bef"
  enabled      = "true"
  freeform_tags = {
  }
  #route_table_id = <<Optional value not found in discovery>>
  vcn_id = oci_core_vcn.export_oke-vcn-quick-cluster1-c388f9bef.id
}

resource oci_core_internet_gateway export_test-igw {
  compartment_id = oci_artifacts_container_configuration.export_container_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/jungin.hong@oracle.com"
    "Oracle-Tags.CreatedOn" = "2026-01-28T10:41:13.305Z"
  }
  display_name = "test-igw"
  enabled      = "true"
  freeform_tags = {
  }
  #route_table_id = <<Optional value not found in discovery>>
  vcn_id = oci_core_vcn.export_terraform-test-vcn.id
}

resource oci_core_default_dhcp_options export_Default-DHCP-Options-for-oke-vcn-quick-cluster1-c388f9bef {
  compartment_id = oci_artifacts_container_configuration.export_container_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/jungin.hong@oracle.com"
    "Oracle-Tags.CreatedOn" = "2026-02-02T05:24:47.364Z"
  }
  display_name     = "Default DHCP Options for oke-vcn-quick-cluster1-c388f9bef"
  domain_name_type = "CUSTOM_DOMAIN"
  freeform_tags = {
  }
  manage_default_resource_id = "ocid1.dhcpoptions.oc1.ap-chuncheon-1.aaaaaaaap2mhlsgdo5h3mtuynwn2hcepbydexolz3yc4vpsrqk257rxl7m7q"
  options {
    custom_dns_servers = [
    ]
    #search_domain_names = <<Optional value not found in discovery>>
    server_type = "VcnLocalPlusInternet"
    type        = "DomainNameServer"
  }
  options {
    #custom_dns_servers = <<Optional value not found in discovery>>
    search_domain_names = [
      "cluster1.oraclevcn.com",
    ]
    #server_type = <<Optional value not found in discovery>>
    type = "SearchDomain"
  }
}

resource oci_core_default_dhcp_options export_Default-DHCP-Options-for-terraform-test-vcn {
  compartment_id = oci_artifacts_container_configuration.export_container_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/jungin.hong@oracle.com"
    "Oracle-Tags.CreatedOn" = "2026-01-28T10:41:12.822Z"
  }
  display_name     = "Default DHCP Options for terraform-test-vcn"
  domain_name_type = "CUSTOM_DOMAIN"
  freeform_tags = {
  }
  manage_default_resource_id = "ocid1.dhcpoptions.oc1.ap-chuncheon-1.aaaaaaaarydf2wsx66vfx6r7djw36q2qlvdr5hruq6dcxz7uvtnu4mzsddmq"
  options {
    custom_dns_servers = [
    ]
    #search_domain_names = <<Optional value not found in discovery>>
    server_type = "VcnLocalPlusInternet"
    type        = "DomainNameServer"
  }
  options {
    #custom_dns_servers = <<Optional value not found in discovery>>
    search_domain_names = [
      "testvcn.oraclevcn.com",
    ]
    #server_type = <<Optional value not found in discovery>>
    type = "SearchDomain"
  }
}

resource oci_core_vcn export_oke-vcn-quick-cluster1-c388f9bef {
  #byoipv6cidr_details = <<Optional value not found in discovery>>
  #cidr_block = <<Optional value not found in discovery>>
  cidr_blocks = [
    "10.0.0.0/16",
  ]
  compartment_id = oci_artifacts_container_configuration.export_container_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/jungin.hong@oracle.com"
    "Oracle-Tags.CreatedOn" = "2026-02-02T05:24:47.364Z"
  }
  display_name = "oke-vcn-quick-cluster1-c388f9bef"
  dns_label    = "cluster1"
  freeform_tags = {
  }
  ipv6private_cidr_blocks = [
  ]
  #is_ipv6enabled = <<Optional value not found in discovery>>
  #is_oracle_gua_allocation_enabled = <<Optional value not found in discovery>>
  security_attributes = {
  }
}

resource oci_core_vcn export_terraform-test-vcn {
  #byoipv6cidr_details = <<Optional value not found in discovery>>
  #cidr_block = <<Optional value not found in discovery>>
  cidr_blocks = [
    "192.0.0.0/16",
  ]
  compartment_id = oci_artifacts_container_configuration.export_container_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/jungin.hong@oracle.com"
    "Oracle-Tags.CreatedOn" = "2026-01-28T10:41:12.822Z"
  }
  display_name = "terraform-test-vcn"
  dns_label    = "testvcn"
  freeform_tags = {
  }
  ipv6private_cidr_blocks = [
  ]
  #is_ipv6enabled = <<Optional value not found in discovery>>
  #is_oracle_gua_allocation_enabled = <<Optional value not found in discovery>>
  security_attributes = {
  }
}

resource oci_core_subnet export_oke-nodesubnet-quick-cluster1-c388f9bef-regional {
  #availability_domain = <<Optional value not found in discovery>>
  cidr_block     = "10.0.10.0/24"
  compartment_id = oci_artifacts_container_configuration.export_container_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/jungin.hong@oracle.com"
    "Oracle-Tags.CreatedOn" = "2026-02-02T05:24:48.715Z"
  }
  dhcp_options_id = oci_core_default_dhcp_options.export_Default-DHCP-Options-for-oke-vcn-quick-cluster1-c388f9bef.id
  display_name    = "oke-nodesubnet-quick-cluster1-c388f9bef-regional"
  dns_label       = "sub0737b9ea5"
  freeform_tags = {
  }
  ipv4cidr_blocks = [
    "10.0.10.0/24",
  ]
  #ipv6cidr_block = <<Optional value not found in discovery>>
  ipv6cidr_blocks = [
  ]
  prohibit_internet_ingress  = "true"
  prohibit_public_ip_on_vnic = "true"
  route_table_id             = oci_core_route_table.export_oke-private-routetable-cluster1-c388f9bef.id
  security_list_ids = [
    oci_core_security_list.export_oke-nodeseclist-quick-cluster1-c388f9bef.id,
  ]
  vcn_id = oci_core_vcn.export_oke-vcn-quick-cluster1-c388f9bef.id
}

resource oci_core_subnet export_oke-k8sApiEndpoint-subnet-quick-cluster1-c388f9bef-regional {
  #availability_domain = <<Optional value not found in discovery>>
  cidr_block     = "10.0.0.0/28"
  compartment_id = oci_artifacts_container_configuration.export_container_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/jungin.hong@oracle.com"
    "Oracle-Tags.CreatedOn" = "2026-02-02T05:24:48.715Z"
  }
  dhcp_options_id = oci_core_default_dhcp_options.export_Default-DHCP-Options-for-oke-vcn-quick-cluster1-c388f9bef.id
  display_name    = "oke-k8sApiEndpoint-subnet-quick-cluster1-c388f9bef-regional"
  dns_label       = "sub09a2af9fe"
  freeform_tags = {
  }
  ipv4cidr_blocks = [
    "10.0.0.0/28",
  ]
  #ipv6cidr_block = <<Optional value not found in discovery>>
  ipv6cidr_blocks = [
  ]
  prohibit_internet_ingress  = "false"
  prohibit_public_ip_on_vnic = "false"
  route_table_id             = oci_core_vcn.export_oke-vcn-quick-cluster1-c388f9bef.default_route_table_id
  security_list_ids = [
    oci_core_security_list.export_oke-k8sApiEndpoint-quick-cluster1-c388f9bef.id,
  ]
  vcn_id = oci_core_vcn.export_oke-vcn-quick-cluster1-c388f9bef.id
}

resource oci_core_subnet export_oke-svclbsubnet-quick-cluster1-c388f9bef-regional {
  #availability_domain = <<Optional value not found in discovery>>
  cidr_block     = "10.0.20.0/24"
  compartment_id = oci_artifacts_container_configuration.export_container_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/jungin.hong@oracle.com"
    "Oracle-Tags.CreatedOn" = "2026-02-02T05:24:48.680Z"
  }
  dhcp_options_id = oci_core_default_dhcp_options.export_Default-DHCP-Options-for-oke-vcn-quick-cluster1-c388f9bef.id
  display_name    = "oke-svclbsubnet-quick-cluster1-c388f9bef-regional"
  dns_label       = "lbsub9bd977b5f"
  freeform_tags = {
  }
  ipv4cidr_blocks = [
    "10.0.20.0/24",
  ]
  #ipv6cidr_block = <<Optional value not found in discovery>>
  ipv6cidr_blocks = [
  ]
  prohibit_internet_ingress  = "false"
  prohibit_public_ip_on_vnic = "false"
  route_table_id             = oci_core_vcn.export_oke-vcn-quick-cluster1-c388f9bef.default_route_table_id
  security_list_ids = [
    oci_core_vcn.export_oke-vcn-quick-cluster1-c388f9bef.default_security_list_id,
  ]
  vcn_id = oci_core_vcn.export_oke-vcn-quick-cluster1-c388f9bef.id
}

resource oci_core_subnet export_private-subnet {
  #availability_domain = <<Optional value not found in discovery>>
  cidr_block     = "192.0.10.0/24"
  compartment_id = oci_artifacts_container_configuration.export_container_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/jungin.hong@oracle.com"
    "Oracle-Tags.CreatedOn" = "2026-01-30T05:06:03.775Z"
  }
  dhcp_options_id = oci_core_default_dhcp_options.export_Default-DHCP-Options-for-terraform-test-vcn.id
  display_name    = "private-subnet"
  dns_label       = "private"
  freeform_tags = {
  }
  ipv4cidr_blocks = [
    "192.0.10.0/24",
  ]
  #ipv6cidr_block = <<Optional value not found in discovery>>
  ipv6cidr_blocks = [
  ]
  prohibit_internet_ingress  = "true"
  prohibit_public_ip_on_vnic = "true"
  route_table_id             = oci_core_route_table.export_private-rt.id
  security_list_ids = [
    oci_core_security_list.export_oke-worker-security-list.id,
    oci_core_vcn.export_terraform-test-vcn.default_security_list_id,
  ]
  vcn_id = oci_core_vcn.export_terraform-test-vcn.id
}

resource oci_core_subnet export_public-subnet {
  #availability_domain = <<Optional value not found in discovery>>
  cidr_block     = "192.0.1.0/24"
  compartment_id = oci_artifacts_container_configuration.export_container_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/jungin.hong@oracle.com"
    "Oracle-Tags.CreatedOn" = "2026-01-28T10:41:14.117Z"
  }
  dhcp_options_id = oci_core_default_dhcp_options.export_Default-DHCP-Options-for-terraform-test-vcn.id
  display_name    = "public-subnet"
  dns_label       = "public"
  freeform_tags = {
  }
  ipv4cidr_blocks = [
    "192.0.1.0/24",
  ]
  #ipv6cidr_block = <<Optional value not found in discovery>>
  ipv6cidr_blocks = [
  ]
  prohibit_internet_ingress  = "false"
  prohibit_public_ip_on_vnic = "false"
  route_table_id             = oci_core_route_table.export_public-rt.id
  security_list_ids = [
    oci_core_vcn.export_terraform-test-vcn.default_security_list_id,
  ]
  vcn_id = oci_core_vcn.export_terraform-test-vcn.id
}

resource oci_core_public_ip export_Floating-Public-IP-for-cluster-ocid1-cluster-oc1-ap-chuncheon-1-aaaaaaaadti2jg5iwumyv3lgabbn2gt6r7s35z5lzshour5igc2jaitlhu7a {
  compartment_id = oci_artifacts_container_configuration.export_container_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/jungin.hong@oracle.com"
    "Oracle-Tags.CreatedOn" = "2026-02-02T05:25:00.619Z"
  }
  display_name = "Floating Public IP for cluster ocid1.cluster.oc1.ap-chuncheon-1.aaaaaaaadti2jg5iwumyv3lgabbn2gt6r7s35z5lzshour5igc2jaitlhu7a"
  freeform_tags = {
  }
  lifetime      = "RESERVED"
  private_ip_id = oci_core_private_ip.export_Service-VNIC-for-cluster-ocid1-cluster-oc1-ap-chuncheon-1-aaaaaaaadti2jg5iwumyv3lgabbn2gt6r7s35z5lzshour5igc2jaitlhu7a.id
  #public_ip_pool_id = <<Optional value not found in discovery>>
}

resource oci_core_private_ip export_Service-VNIC-for-virtual-node-ocid1-virtualnode-oc1-ap-chuncheon-1-amaaaaaavsea7yiawkxeazxjxeyrxan2vnfpejrdmpa3trwktj7cp2y22kza {
  cidr_prefix_length = "32"
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/jungin.hong@oracle.com"
    "Oracle-Tags.CreatedOn" = "2026-02-02T05:31:48.927Z"
  }
  display_name = "Service VNIC for virtual node ocid1.virtualnode.oc1.ap-chuncheon-1.amaaaaaavsea7yiawkxeazxjxeyrxan2vnfpejrdmpa3trwktj7cp2y22kza"
  freeform_tags = {
  }
  hostname_label = "host-10-0-10-193"
  ip_address     = "10.0.10.193"
  #ipv4subnet_cidr_at_creation = <<Optional value not found in discovery>>
  lifetime = "EPHEMERAL"
  #route_table_id = <<Optional value not found in discovery>>
  subnet_id = oci_core_subnet.export_oke-nodesubnet-quick-cluster1-c388f9bef-regional.id
  #vlan_id = <<Optional value not found in discovery>>
  vnic_id = "ocid1.vnic.oc1.ap-chuncheon-1.ab4w4ljre3gqrbbi4qcmffnw4dmqqcuq3p4h4wgtkki7a3v2cseili2w3kpq"
}

resource oci_core_private_ip export_Service-VNIC-for-virtual-node-ocid1-virtualnode-oc1-ap-chuncheon-1-amaaaaaavsea7yia3cyyar7dxue5d3wwz722okzj7c7rrm7tctvyuslcy4ia {
  cidr_prefix_length = "32"
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/jungin.hong@oracle.com"
    "Oracle-Tags.CreatedOn" = "2026-02-02T05:31:48.837Z"
  }
  display_name = "Service VNIC for virtual node ocid1.virtualnode.oc1.ap-chuncheon-1.amaaaaaavsea7yia3cyyar7dxue5d3wwz722okzj7c7rrm7tctvyuslcy4ia"
  freeform_tags = {
  }
  hostname_label = "host-10-0-10-235"
  ip_address     = "10.0.10.235"
  #ipv4subnet_cidr_at_creation = <<Optional value not found in discovery>>
  lifetime = "EPHEMERAL"
  #route_table_id = <<Optional value not found in discovery>>
  subnet_id = oci_core_subnet.export_oke-nodesubnet-quick-cluster1-c388f9bef-regional.id
  #vlan_id = <<Optional value not found in discovery>>
  vnic_id = "ocid1.vnic.oc1.ap-chuncheon-1.ab4w4ljrx5bpj344j6pwixcjwkdxuoqfc637msuehqigzembzi2rudwb5n7q"
}

resource oci_core_private_ip export_Service-VNIC-for-virtual-node-ocid1-virtualnode-oc1-ap-chuncheon-1-amaaaaaavsea7yiaamgy4yaznnt6urng2cg5yy52dq2ovdaa4b7q5oznz3uq {
  cidr_prefix_length = "32"
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/jungin.hong@oracle.com"
    "Oracle-Tags.CreatedOn" = "2026-02-02T05:31:48.846Z"
  }
  display_name = "Service VNIC for virtual node ocid1.virtualnode.oc1.ap-chuncheon-1.amaaaaaavsea7yiaamgy4yaznnt6urng2cg5yy52dq2ovdaa4b7q5oznz3uq"
  freeform_tags = {
  }
  hostname_label = "host-10-0-10-241"
  ip_address     = "10.0.10.241"
  #ipv4subnet_cidr_at_creation = <<Optional value not found in discovery>>
  lifetime = "EPHEMERAL"
  #route_table_id = <<Optional value not found in discovery>>
  subnet_id = oci_core_subnet.export_oke-nodesubnet-quick-cluster1-c388f9bef-regional.id
  #vlan_id = <<Optional value not found in discovery>>
  vnic_id = "ocid1.vnic.oc1.ap-chuncheon-1.ab4w4ljrdm72apfvca2d5l52ejis7nmjj5iv6u6lzs2fr6u656tp6cx2c2yq"
}

resource oci_core_route_table export_oke-private-routetable-cluster1-c388f9bef {
  compartment_id = oci_artifacts_container_configuration.export_container_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/jungin.hong@oracle.com"
    "Oracle-Tags.CreatedOn" = "2026-02-02T05:24:50.269Z"
  }
  display_name = "oke-private-routetable-cluster1-c388f9bef"
  freeform_tags = {
  }
  route_rules {
    description       = "traffic to the internet"
    destination       = "0.0.0.0/0"
    destination_type  = "CIDR_BLOCK"
    network_entity_id = oci_core_nat_gateway.export_oke-ngw-quick-cluster1-c388f9bef.id
    route_type        = "STATIC"
  }
  route_rules {
    description       = "traffic to OCI services"
    destination       = "all-yny-services-in-oracle-services-network"
    destination_type  = "SERVICE_CIDR_BLOCK"
    network_entity_id = oci_core_service_gateway.export_oke-sgw-quick-cluster1-c388f9bef.id
    route_type        = "STATIC"
  }
  vcn_id = oci_core_vcn.export_oke-vcn-quick-cluster1-c388f9bef.id
}

resource oci_core_default_route_table export_oke-public-routetable-cluster1-c388f9bef {
  compartment_id = oci_artifacts_container_configuration.export_container_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/jungin.hong@oracle.com"
    "Oracle-Tags.CreatedOn" = "2026-02-02T05:24:47.364Z"
  }
  display_name = "oke-public-routetable-cluster1-c388f9bef"
  freeform_tags = {
  }
  manage_default_resource_id = oci_core_vcn.export_oke-vcn-quick-cluster1-c388f9bef.default_route_table_id
  route_rules {
    description       = "traffic to/from internet"
    destination       = "0.0.0.0/0"
    destination_type  = "CIDR_BLOCK"
    network_entity_id = oci_core_internet_gateway.export_oke-igw-quick-cluster1-c388f9bef.id
    route_type        = "STATIC"
  }
}

resource oci_core_route_table export_private-rt {
  compartment_id = oci_artifacts_container_configuration.export_container_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/jungin.hong@oracle.com"
    "Oracle-Tags.CreatedOn" = "2026-01-30T05:06:03.244Z"
  }
  display_name = "private-rt"
  freeform_tags = {
  }
  route_rules {
    #description = <<Optional value not found in discovery>>
    destination       = "all-yny-services-in-oracle-services-network"
    destination_type  = "SERVICE_CIDR_BLOCK"
    network_entity_id = oci_core_service_gateway.export_test-sgw.id
    route_type        = "STATIC"
  }
  route_rules {
    #description = <<Optional value not found in discovery>>
    destination       = "0.0.0.0/0"
    destination_type  = "CIDR_BLOCK"
    network_entity_id = oci_core_nat_gateway.export_test-nat.id
    route_type        = "STATIC"
  }
  vcn_id = oci_core_vcn.export_terraform-test-vcn.id
}

resource oci_core_route_table export_public-rt {
  compartment_id = oci_artifacts_container_configuration.export_container_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/jungin.hong@oracle.com"
    "Oracle-Tags.CreatedOn" = "2026-01-28T10:41:13.748Z"
  }
  display_name = "public-rt"
  freeform_tags = {
  }
  route_rules {
    #description = <<Optional value not found in discovery>>
    destination       = "0.0.0.0/0"
    destination_type  = "CIDR_BLOCK"
    network_entity_id = oci_core_internet_gateway.export_test-igw.id
    route_type        = "STATIC"
  }
  vcn_id = oci_core_vcn.export_terraform-test-vcn.id
}

resource oci_core_default_route_table export_Default-Route-Table-for-terraform-test-vcn {
  compartment_id = oci_artifacts_container_configuration.export_container_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/jungin.hong@oracle.com"
    "Oracle-Tags.CreatedOn" = "2026-01-28T10:41:12.822Z"
  }
  display_name = "Default Route Table for terraform-test-vcn"
  freeform_tags = {
  }
  manage_default_resource_id = oci_core_vcn.export_terraform-test-vcn.default_route_table_id
}

resource oci_core_security_list export_oke-k8sApiEndpoint-quick-cluster1-c388f9bef {
  compartment_id = oci_artifacts_container_configuration.export_container_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/jungin.hong@oracle.com"
    "Oracle-Tags.CreatedOn" = "2026-02-02T05:24:47.993Z"
  }
  display_name = "oke-k8sApiEndpoint-quick-cluster1-c388f9bef"
  egress_security_rules {
    description      = "Allow Kubernetes Control Plane to communicate with OKE"
    destination      = "all-yny-services-in-oracle-services-network"
    destination_type = "SERVICE_CIDR_BLOCK"
    #icmp_options = <<Optional value not found in discovery>>
    protocol  = "6"
    stateless = "false"
    tcp_options {
      max = "443"
      min = "443"
      #source_port_range = <<Optional value not found in discovery>>
    }
    #udp_options = <<Optional value not found in discovery>>
  }
  egress_security_rules {
    description      = "All traffic to worker nodes"
    destination      = "10.0.10.0/24"
    destination_type = "CIDR_BLOCK"
    #icmp_options = <<Optional value not found in discovery>>
    protocol  = "6"
    stateless = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  egress_security_rules {
    description      = "Path discovery"
    destination      = "10.0.10.0/24"
    destination_type = "CIDR_BLOCK"
    icmp_options {
      code = "4"
      type = "3"
    }
    protocol  = "1"
    stateless = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  freeform_tags = {
  }
  ingress_security_rules {
    description = "External access to Kubernetes API endpoint"
    #icmp_options = <<Optional value not found in discovery>>
    protocol    = "6"
    source      = "0.0.0.0/0"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    tcp_options {
      max = "6443"
      min = "6443"
      #source_port_range = <<Optional value not found in discovery>>
    }
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    description = "Kubernetes worker to Kubernetes API endpoint communication"
    #icmp_options = <<Optional value not found in discovery>>
    protocol    = "6"
    source      = "10.0.10.0/24"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    tcp_options {
      max = "6443"
      min = "6443"
      #source_port_range = <<Optional value not found in discovery>>
    }
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    description = "Kubernetes worker to control plane communication"
    #icmp_options = <<Optional value not found in discovery>>
    protocol    = "6"
    source      = "10.0.10.0/24"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    tcp_options {
      max = "12250"
      min = "12250"
      #source_port_range = <<Optional value not found in discovery>>
    }
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    description = "Path discovery"
    icmp_options {
      code = "4"
      type = "3"
    }
    protocol    = "1"
    source      = "10.0.10.0/24"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  vcn_id = oci_core_vcn.export_oke-vcn-quick-cluster1-c388f9bef.id
}

resource oci_core_security_list export_oke-nodeseclist-quick-cluster1-c388f9bef {
  compartment_id = oci_artifacts_container_configuration.export_container_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/jungin.hong@oracle.com"
    "Oracle-Tags.CreatedOn" = "2026-02-02T05:24:47.897Z"
  }
  display_name = "oke-nodeseclist-quick-cluster1-c388f9bef"
  egress_security_rules {
    description      = "Allow pods on one worker node to communicate with pods on other worker nodes"
    destination      = "10.0.10.0/24"
    destination_type = "CIDR_BLOCK"
    #icmp_options = <<Optional value not found in discovery>>
    protocol  = "all"
    stateless = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  egress_security_rules {
    description      = "Access to Kubernetes API Endpoint"
    destination      = "10.0.0.0/28"
    destination_type = "CIDR_BLOCK"
    #icmp_options = <<Optional value not found in discovery>>
    protocol  = "6"
    stateless = "false"
    tcp_options {
      max = "6443"
      min = "6443"
      #source_port_range = <<Optional value not found in discovery>>
    }
    #udp_options = <<Optional value not found in discovery>>
  }
  egress_security_rules {
    description      = "Kubernetes worker to control plane communication"
    destination      = "10.0.0.0/28"
    destination_type = "CIDR_BLOCK"
    #icmp_options = <<Optional value not found in discovery>>
    protocol  = "6"
    stateless = "false"
    tcp_options {
      max = "12250"
      min = "12250"
      #source_port_range = <<Optional value not found in discovery>>
    }
    #udp_options = <<Optional value not found in discovery>>
  }
  egress_security_rules {
    description      = "Path discovery"
    destination      = "10.0.0.0/28"
    destination_type = "CIDR_BLOCK"
    icmp_options {
      code = "4"
      type = "3"
    }
    protocol  = "1"
    stateless = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  egress_security_rules {
    description      = "Allow nodes to communicate with OKE to ensure correct start-up and continued functioning"
    destination      = "all-yny-services-in-oracle-services-network"
    destination_type = "SERVICE_CIDR_BLOCK"
    #icmp_options = <<Optional value not found in discovery>>
    protocol  = "6"
    stateless = "false"
    tcp_options {
      max = "443"
      min = "443"
      #source_port_range = <<Optional value not found in discovery>>
    }
    #udp_options = <<Optional value not found in discovery>>
  }
  egress_security_rules {
    description      = "ICMP Access from Kubernetes Control Plane"
    destination      = "0.0.0.0/0"
    destination_type = "CIDR_BLOCK"
    icmp_options {
      code = "4"
      type = "3"
    }
    protocol  = "1"
    stateless = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  egress_security_rules {
    description      = "Worker Nodes access to Internet"
    destination      = "0.0.0.0/0"
    destination_type = "CIDR_BLOCK"
    #icmp_options = <<Optional value not found in discovery>>
    protocol  = "all"
    stateless = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  freeform_tags = {
  }
  ingress_security_rules {
    description = "Allow pods on one worker node to communicate with pods on other worker nodes"
    #icmp_options = <<Optional value not found in discovery>>
    protocol    = "all"
    source      = "10.0.10.0/24"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    description = "Path discovery"
    icmp_options {
      code = "4"
      type = "3"
    }
    protocol    = "1"
    source      = "10.0.0.0/28"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    description = "TCP access from Kubernetes Control Plane"
    #icmp_options = <<Optional value not found in discovery>>
    protocol    = "6"
    source      = "10.0.0.0/28"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    description = "Inbound SSH traffic to worker nodes"
    #icmp_options = <<Optional value not found in discovery>>
    protocol    = "6"
    source      = "0.0.0.0/0"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    tcp_options {
      max = "22"
      min = "22"
      #source_port_range = <<Optional value not found in discovery>>
    }
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    description = "Allow TCP traffic from Load Balancers to node ports"
    #icmp_options = <<Optional value not found in discovery>>
    protocol    = "6"
    source      = "10.0.20.0/24"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    tcp_options {
      max = "32767"
      min = "30000"
      #source_port_range = <<Optional value not found in discovery>>
    }
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    description = "Allow TCP traffic from Load Balancers to pod's healthcheck port"
    #icmp_options = <<Optional value not found in discovery>>
    protocol    = "6"
    source      = "10.0.20.0/24"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    tcp_options {
      max = "10256"
      min = "10256"
      #source_port_range = <<Optional value not found in discovery>>
    }
    #udp_options = <<Optional value not found in discovery>>
  }
  vcn_id = oci_core_vcn.export_oke-vcn-quick-cluster1-c388f9bef.id
}

resource oci_core_default_security_list export_oke-svclbseclist-quick-cluster1-c388f9bef {
  compartment_id = oci_artifacts_container_configuration.export_container_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/jungin.hong@oracle.com"
    "Oracle-Tags.CreatedOn" = "2026-02-02T05:24:47.364Z"
  }
  display_name = "oke-svclbseclist-quick-cluster1-c388f9bef"
  egress_security_rules {
    description      = "Allow TCP traffic from Load Balancers to node ports"
    destination      = "10.0.10.0/24"
    destination_type = "CIDR_BLOCK"
    #icmp_options = <<Optional value not found in discovery>>
    protocol  = "6"
    stateless = "false"
    tcp_options {
      max = "32767"
      min = "30000"
      #source_port_range = <<Optional value not found in discovery>>
    }
    #udp_options = <<Optional value not found in discovery>>
  }
  egress_security_rules {
    description      = "Allow TCP traffic from Load Balancers to pod's healthcheck port"
    destination      = "10.0.20.0/24"
    destination_type = "CIDR_BLOCK"
    #icmp_options = <<Optional value not found in discovery>>
    protocol  = "6"
    stateless = "false"
    tcp_options {
      max = "10256"
      min = "10256"
      #source_port_range = <<Optional value not found in discovery>>
    }
    #udp_options = <<Optional value not found in discovery>>
  }
  freeform_tags = {
  }
  ingress_security_rules {
    description = "Allow traffic from Internet to Load Balancers on TCP/80"
    #icmp_options = <<Optional value not found in discovery>>
    protocol    = "6"
    source      = "0.0.0.0/0"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    tcp_options {
      max = "80"
      min = "80"
      #source_port_range = <<Optional value not found in discovery>>
    }
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    description = "Allow traffic from Internet to Load Balancers on TCP/443"
    #icmp_options = <<Optional value not found in discovery>>
    protocol    = "6"
    source      = "0.0.0.0/0"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    tcp_options {
      max = "443"
      min = "443"
      #source_port_range = <<Optional value not found in discovery>>
    }
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    description = "Allow traffic from Internet to Load Balancers on TCP/8080"
    #icmp_options = <<Optional value not found in discovery>>
    protocol    = "6"
    source      = "0.0.0.0/0"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    tcp_options {
      max = "8080"
      min = "8080"
      #source_port_range = <<Optional value not found in discovery>>
    }
    #udp_options = <<Optional value not found in discovery>>
  }
  manage_default_resource_id = oci_core_vcn.export_oke-vcn-quick-cluster1-c388f9bef.default_security_list_id
}

resource oci_core_security_list export_oke-worker-security-list {
  compartment_id = oci_artifacts_container_configuration.export_container_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/jungin.hong@oracle.com"
    "Oracle-Tags.CreatedOn" = "2026-01-30T05:05:57.638Z"
  }
  display_name = "oke-worker-security-list"
  egress_security_rules {
    #description = <<Optional value not found in discovery>>
    destination      = "0.0.0.0/0"
    destination_type = "CIDR_BLOCK"
    #icmp_options = <<Optional value not found in discovery>>
    protocol  = "all"
    stateless = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  egress_security_rules {
    #description = <<Optional value not found in discovery>>
    destination      = "all-yny-services-in-oracle-services-network"
    destination_type = "SERVICE_CIDR_BLOCK"
    #icmp_options = <<Optional value not found in discovery>>
    protocol  = "all"
    stateless = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  freeform_tags = {
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    #icmp_options = <<Optional value not found in discovery>>
    protocol    = "6"
    source      = "192.0.0.0/16"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    tcp_options {
      max = "22"
      min = "22"
      #source_port_range = <<Optional value not found in discovery>>
    }
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    #icmp_options = <<Optional value not found in discovery>>
    protocol    = "all"
    source      = "192.0.0.0/16"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  vcn_id = oci_core_vcn.export_terraform-test-vcn.id
}

resource oci_core_default_security_list export_Default-Security-List-for-terraform-test-vcn {
  compartment_id = oci_artifacts_container_configuration.export_container_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/jungin.hong@oracle.com"
    "Oracle-Tags.CreatedOn" = "2026-01-28T10:41:12.822Z"
  }
  display_name = "Default Security List for terraform-test-vcn"
  egress_security_rules {
    #description = <<Optional value not found in discovery>>
    destination      = "0.0.0.0/0"
    destination_type = "CIDR_BLOCK"
    #icmp_options = <<Optional value not found in discovery>>
    protocol  = "all"
    stateless = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  freeform_tags = {
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    #icmp_options = <<Optional value not found in discovery>>
    protocol    = "6"
    source      = "0.0.0.0/0"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    tcp_options {
      max = "22"
      min = "22"
      #source_port_range = <<Optional value not found in discovery>>
    }
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    icmp_options {
      code = "4"
      type = "3"
    }
    protocol    = "1"
    source      = "0.0.0.0/0"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    icmp_options {
      code = "-1"
      type = "3"
    }
    protocol    = "1"
    source      = "192.0.0.0/16"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  manage_default_resource_id = oci_core_vcn.export_terraform-test-vcn.default_security_list_id
}

resource oci_core_private_ip export_Service-VNIC-for-cluster-ocid1-cluster-oc1-ap-chuncheon-1-aaaaaaaadti2jg5iwumyv3lgabbn2gt6r7s35z5lzshour5igc2jaitlhu7a {
  cidr_prefix_length = "32"
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/jungin.hong@oracle.com"
    "Oracle-Tags.CreatedOn" = "2026-02-02T05:24:59.808Z"
  }
  display_name = "Service VNIC for cluster ocid1.cluster.oc1.ap-chuncheon-1.aaaaaaaadti2jg5iwumyv3lgabbn2gt6r7s35z5lzshour5igc2jaitlhu7a"
  freeform_tags = {
  }
  hostname_label = "c2jaitlhu7a"
  ip_address     = "10.0.0.10"
  #ipv4subnet_cidr_at_creation = <<Optional value not found in discovery>>
  lifetime = "EPHEMERAL"
  #route_table_id = <<Optional value not found in discovery>>
  subnet_id = oci_core_subnet.export_oke-k8sApiEndpoint-subnet-quick-cluster1-c388f9bef-regional.id
  #vlan_id = <<Optional value not found in discovery>>
  vnic_id = "ocid1.vnic.oc1.ap-chuncheon-1.ab4w4ljr2x7ub4qtkp6ftst25eo4t7cis5m3gxoopv45jqcznjnoqrtw2e7a"
}

resource oci_core_service_gateway export_oke-sgw-quick-cluster1-c388f9bef {
  compartment_id = oci_artifacts_container_configuration.export_container_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/jungin.hong@oracle.com"
    "Oracle-Tags.CreatedOn" = "2026-02-02T05:24:47.996Z"
  }
  display_name = "oke-sgw-quick-cluster1-c388f9bef"
  freeform_tags = {
  }
  #route_table_id = <<Optional value not found in discovery>>
  services {
    service_id = "ocid1.service.oc1.ap-chuncheon-1.aaaaaaaav26pw33pfolcobpj62iy6pq2xkkzeiizc2m64i2elbdj5mw4dnra"
  }
  vcn_id = oci_core_vcn.export_oke-vcn-quick-cluster1-c388f9bef.id
}

resource oci_core_service_gateway export_test-sgw {
  compartment_id = oci_artifacts_container_configuration.export_container_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/jungin.hong@oracle.com"
    "Oracle-Tags.CreatedOn" = "2026-01-30T05:05:57.666Z"
  }
  display_name = "test-sgw"
  freeform_tags = {
  }
  #route_table_id = <<Optional value not found in discovery>>
  services {
    service_id = "ocid1.service.oc1.ap-chuncheon-1.aaaaaaaav26pw33pfolcobpj62iy6pq2xkkzeiizc2m64i2elbdj5mw4dnra"
  }
  vcn_id = oci_core_vcn.export_terraform-test-vcn.id
}

