## This configuration was generated by terraform-provider-oci

resource oci_dns_view export_oke-vcn-quick-cluster1-c388f9bef_1 {
  compartment_id = oci_artifacts_container_configuration.export_container_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/jungin.hong@oracle.com"
    "Oracle-Tags.CreatedOn" = "2026-02-02T05:24:47.364Z"
  }
  display_name = "oke-vcn-quick-cluster1-c388f9bef"
  freeform_tags = {
  }
  #scope = <<Optional value not found in discovery>>
}

resource oci_dns_view export_terraform-test-vcn_1 {
  compartment_id = oci_artifacts_container_configuration.export_container_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/jungin.hong@oracle.com"
    "Oracle-Tags.CreatedOn" = "2026-01-28T10:41:12.822Z"
  }
  display_name = "terraform-test-vcn"
  freeform_tags = {
  }
  #scope = <<Optional value not found in discovery>>
}

resource oci_dns_resolver export_oke-vcn-quick-cluster1-c388f9bef_2 {
  compartment_id = oci_artifacts_container_configuration.export_container_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/jungin.hong@oracle.com"
    "Oracle-Tags.CreatedOn" = "2026-02-02T05:24:47.364Z"
  }
  display_name = "oke-vcn-quick-cluster1-c388f9bef"
  freeform_tags = {
  }
  resolver_id = "ocid1.dnsresolver.oc1.ap-chuncheon-1.amaaaaaavsea7yiatko46izmuq47au2fkggrllm53555axxrh3x5twtin7dq"
  #scope = <<Optional value not found in discovery>>
}

resource oci_dns_resolver export_terraform-test-vcn_2 {
  compartment_id = oci_artifacts_container_configuration.export_container_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/jungin.hong@oracle.com"
    "Oracle-Tags.CreatedOn" = "2026-01-28T10:41:12.822Z"
  }
  display_name = "terraform-test-vcn"
  freeform_tags = {
  }
  resolver_id = "ocid1.dnsresolver.oc1.ap-chuncheon-1.amaaaaaavsea7yiats3tdkc2sqwpql3miv2fi4arwyjodyn4xqugxl6tu2ma"
  #scope = <<Optional value not found in discovery>>
}

resource oci_dns_zone export_sub0737b9ea5-cluster1-oraclevcn-com {
  compartment_id = oci_artifacts_container_configuration.export_container_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/jungin.hong@oracle.com"
    "Oracle-Tags.CreatedOn" = "2026-02-02T05:24:48.715Z"
  }
  dnssec_state = "DISABLED"
  freeform_tags = {
  }
  name      = "sub0737b9ea5.cluster1.oraclevcn.com"
  scope     = "PRIVATE"
  view_id   = oci_dns_view.export_oke-vcn-quick-cluster1-c388f9bef_1.id
  zone_type = "PRIMARY"
}

resource oci_dns_zone export_sub09a2af9fe-cluster1-oraclevcn-com {
  compartment_id = oci_artifacts_container_configuration.export_container_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/jungin.hong@oracle.com"
    "Oracle-Tags.CreatedOn" = "2026-02-02T05:24:48.715Z"
  }
  dnssec_state = "DISABLED"
  freeform_tags = {
  }
  name      = "sub09a2af9fe.cluster1.oraclevcn.com"
  scope     = "PRIVATE"
  view_id   = oci_dns_view.export_oke-vcn-quick-cluster1-c388f9bef_1.id
  zone_type = "PRIMARY"
}

resource oci_dns_zone export_lbsub9bd977b5f-cluster1-oraclevcn-com {
  compartment_id = oci_artifacts_container_configuration.export_container_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/jungin.hong@oracle.com"
    "Oracle-Tags.CreatedOn" = "2026-02-02T05:24:48.680Z"
  }
  dnssec_state = "DISABLED"
  freeform_tags = {
  }
  name      = "lbsub9bd977b5f.cluster1.oraclevcn.com"
  scope     = "PRIVATE"
  view_id   = oci_dns_view.export_oke-vcn-quick-cluster1-c388f9bef_1.id
  zone_type = "PRIMARY"
}

resource oci_dns_zone export_0-10-in-addr-arpa {
  compartment_id = oci_artifacts_container_configuration.export_container_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/jungin.hong@oracle.com"
    "Oracle-Tags.CreatedOn" = "2026-02-02T05:24:47.364Z"
  }
  dnssec_state = "DISABLED"
  freeform_tags = {
  }
  name      = "0.10.in-addr.arpa"
  scope     = "PRIVATE"
  view_id   = oci_dns_view.export_oke-vcn-quick-cluster1-c388f9bef_1.id
  zone_type = "PRIMARY"
}

resource oci_dns_zone export_private-testvcn-oraclevcn-com {
  compartment_id = oci_artifacts_container_configuration.export_container_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/jungin.hong@oracle.com"
    "Oracle-Tags.CreatedOn" = "2026-01-30T05:06:03.775Z"
  }
  dnssec_state = "DISABLED"
  freeform_tags = {
  }
  name      = "private.testvcn.oraclevcn.com"
  scope     = "PRIVATE"
  view_id   = oci_dns_view.export_terraform-test-vcn_1.id
  zone_type = "PRIMARY"
}

resource oci_dns_zone export_public-testvcn-oraclevcn-com {
  compartment_id = oci_artifacts_container_configuration.export_container_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/jungin.hong@oracle.com"
    "Oracle-Tags.CreatedOn" = "2026-01-28T10:41:14.117Z"
  }
  dnssec_state = "DISABLED"
  freeform_tags = {
  }
  name      = "public.testvcn.oraclevcn.com"
  scope     = "PRIVATE"
  view_id   = oci_dns_view.export_terraform-test-vcn_1.id
  zone_type = "PRIMARY"
}

resource oci_dns_zone export_0-192-in-addr-arpa {
  compartment_id = oci_artifacts_container_configuration.export_container_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/jungin.hong@oracle.com"
    "Oracle-Tags.CreatedOn" = "2026-01-28T10:41:12.822Z"
  }
  dnssec_state = "DISABLED"
  freeform_tags = {
  }
  name      = "0.192.in-addr.arpa"
  scope     = "PRIVATE"
  view_id   = oci_dns_view.export_terraform-test-vcn_1.id
  zone_type = "PRIMARY"
}

resource oci_dns_rrset export_sub0737b9ea5-cluster1-oraclevcn-com_host--10--0--10--108-sub0737b9ea5-cluster1-oraclevcn-com_A {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "host-10-0-10-108.sub0737b9ea5.cluster1.oraclevcn.com"
  items {
    domain = "host-10-0-10-108.sub0737b9ea5.cluster1.oraclevcn.com"
    rdata  = "10.0.10.108"
    rtype  = "A"
    ttl    = "300"
  }
  rtype = "A"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_sub0737b9ea5-cluster1-oraclevcn-com.id
}

resource oci_dns_rrset export_sub0737b9ea5-cluster1-oraclevcn-com_host--10--0--10--193-sub0737b9ea5-cluster1-oraclevcn-com_A {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "host-10-0-10-193.sub0737b9ea5.cluster1.oraclevcn.com"
  items {
    domain = "host-10-0-10-193.sub0737b9ea5.cluster1.oraclevcn.com"
    rdata  = "10.0.10.193"
    rtype  = "A"
    ttl    = "300"
  }
  rtype = "A"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_sub0737b9ea5-cluster1-oraclevcn-com.id
}

resource oci_dns_rrset export_sub0737b9ea5-cluster1-oraclevcn-com_host--10--0--10--235-sub0737b9ea5-cluster1-oraclevcn-com_A {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "host-10-0-10-235.sub0737b9ea5.cluster1.oraclevcn.com"
  items {
    domain = "host-10-0-10-235.sub0737b9ea5.cluster1.oraclevcn.com"
    rdata  = "10.0.10.235"
    rtype  = "A"
    ttl    = "300"
  }
  rtype = "A"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_sub0737b9ea5-cluster1-oraclevcn-com.id
}

resource oci_dns_rrset export_sub0737b9ea5-cluster1-oraclevcn-com_host--10--0--10--241-sub0737b9ea5-cluster1-oraclevcn-com_A {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "host-10-0-10-241.sub0737b9ea5.cluster1.oraclevcn.com"
  items {
    domain = "host-10-0-10-241.sub0737b9ea5.cluster1.oraclevcn.com"
    rdata  = "10.0.10.241"
    rtype  = "A"
    ttl    = "300"
  }
  rtype = "A"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_sub0737b9ea5-cluster1-oraclevcn-com.id
}

resource oci_dns_rrset export_sub0737b9ea5-cluster1-oraclevcn-com_sub0737b9ea5-cluster1-oraclevcn-com_NS {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "sub0737b9ea5.cluster1.oraclevcn.com"
  items {
    domain = "sub0737b9ea5.cluster1.oraclevcn.com"
    rdata  = "vcn-dns.oraclevcn.com."
    rtype  = "NS"
    ttl    = "86400"
  }
  rtype = "NS"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_sub0737b9ea5-cluster1-oraclevcn-com.id
}

resource oci_dns_rrset export_sub0737b9ea5-cluster1-oraclevcn-com_sub0737b9ea5-cluster1-oraclevcn-com_SOA {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "sub0737b9ea5.cluster1.oraclevcn.com"
  items {
    domain = "sub0737b9ea5.cluster1.oraclevcn.com"
    rdata  = "vcn-dns.oraclevcn.com. hostmaster.oracle.com. 7 3600 3600 3600 10"
    rtype  = "SOA"
    ttl    = "86400"
  }
  rtype = "SOA"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_sub0737b9ea5-cluster1-oraclevcn-com.id
}

resource oci_dns_rrset export_sub09a2af9fe-cluster1-oraclevcn-com_c2jaitlhu7a-sub09a2af9fe-cluster1-oraclevcn-com_A {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "c2jaitlhu7a.sub09a2af9fe.cluster1.oraclevcn.com"
  items {
    domain = "c2jaitlhu7a.sub09a2af9fe.cluster1.oraclevcn.com"
    rdata  = "10.0.0.10"
    rtype  = "A"
    ttl    = "300"
  }
  rtype = "A"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_sub09a2af9fe-cluster1-oraclevcn-com.id
}

resource oci_dns_rrset export_sub09a2af9fe-cluster1-oraclevcn-com_sub09a2af9fe-cluster1-oraclevcn-com_SOA {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "sub09a2af9fe.cluster1.oraclevcn.com"
  items {
    domain = "sub09a2af9fe.cluster1.oraclevcn.com"
    rdata  = "vcn-dns.oraclevcn.com. hostmaster.oracle.com. 2 3600 3600 3600 10"
    rtype  = "SOA"
    ttl    = "86400"
  }
  rtype = "SOA"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_sub09a2af9fe-cluster1-oraclevcn-com.id
}

resource oci_dns_rrset export_sub09a2af9fe-cluster1-oraclevcn-com_sub09a2af9fe-cluster1-oraclevcn-com_NS {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "sub09a2af9fe.cluster1.oraclevcn.com"
  items {
    domain = "sub09a2af9fe.cluster1.oraclevcn.com"
    rdata  = "vcn-dns.oraclevcn.com."
    rtype  = "NS"
    ttl    = "86400"
  }
  rtype = "NS"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_sub09a2af9fe-cluster1-oraclevcn-com.id
}

resource oci_dns_rrset export_lbsub9bd977b5f-cluster1-oraclevcn-com_lbsub9bd977b5f-cluster1-oraclevcn-com_NS {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "lbsub9bd977b5f.cluster1.oraclevcn.com"
  items {
    domain = "lbsub9bd977b5f.cluster1.oraclevcn.com"
    rdata  = "vcn-dns.oraclevcn.com."
    rtype  = "NS"
    ttl    = "86400"
  }
  rtype = "NS"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_lbsub9bd977b5f-cluster1-oraclevcn-com.id
}

resource oci_dns_rrset export_lbsub9bd977b5f-cluster1-oraclevcn-com_lbsub9bd977b5f-cluster1-oraclevcn-com_SOA {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "lbsub9bd977b5f.cluster1.oraclevcn.com"
  items {
    domain = "lbsub9bd977b5f.cluster1.oraclevcn.com"
    rdata  = "vcn-dns.oraclevcn.com. hostmaster.oracle.com. 1 3600 3600 3600 10"
    rtype  = "SOA"
    ttl    = "86400"
  }
  rtype = "SOA"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_lbsub9bd977b5f-cluster1-oraclevcn-com.id
}

resource oci_dns_rrset export_0-10-in-addr-arpa_0-10-in--addr-arpa_NS {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "0.10.in-addr.arpa"
  items {
    domain = "0.10.in-addr.arpa"
    rdata  = "vcn-dns.oraclevcn.com."
    rtype  = "NS"
    ttl    = "86400"
  }
  rtype = "NS"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_0-10-in-addr-arpa.id
}

resource oci_dns_rrset export_0-10-in-addr-arpa_0-10-in--addr-arpa_SOA {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "0.10.in-addr.arpa"
  items {
    domain = "0.10.in-addr.arpa"
    rdata  = "vcn-dns.oraclevcn.com. hostmaster.oracle.com. 8 3600 3600 3600 10"
    rtype  = "SOA"
    ttl    = "86400"
  }
  rtype = "SOA"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_0-10-in-addr-arpa.id
}

resource oci_dns_rrset export_0-10-in-addr-arpa_10-0-0-10-in--addr-arpa_PTR {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "10.0.0.10.in-addr.arpa"
  items {
    domain = "10.0.0.10.in-addr.arpa"
    rdata  = "c2jaitlhu7a.sub09a2af9fe.cluster1.oraclevcn.com."
    rtype  = "PTR"
    ttl    = "300"
  }
  rtype = "PTR"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_0-10-in-addr-arpa.id
}

resource oci_dns_rrset export_0-10-in-addr-arpa_108-10-0-10-in--addr-arpa_PTR {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "108.10.0.10.in-addr.arpa"
  items {
    domain = "108.10.0.10.in-addr.arpa"
    rdata  = "host-10-0-10-108.sub0737b9ea5.cluster1.oraclevcn.com."
    rtype  = "PTR"
    ttl    = "300"
  }
  rtype = "PTR"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_0-10-in-addr-arpa.id
}

resource oci_dns_rrset export_0-10-in-addr-arpa_193-10-0-10-in--addr-arpa_PTR {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "193.10.0.10.in-addr.arpa"
  items {
    domain = "193.10.0.10.in-addr.arpa"
    rdata  = "host-10-0-10-193.sub0737b9ea5.cluster1.oraclevcn.com."
    rtype  = "PTR"
    ttl    = "300"
  }
  rtype = "PTR"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_0-10-in-addr-arpa.id
}

resource oci_dns_rrset export_0-10-in-addr-arpa_235-10-0-10-in--addr-arpa_PTR {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "235.10.0.10.in-addr.arpa"
  items {
    domain = "235.10.0.10.in-addr.arpa"
    rdata  = "host-10-0-10-235.sub0737b9ea5.cluster1.oraclevcn.com."
    rtype  = "PTR"
    ttl    = "300"
  }
  rtype = "PTR"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_0-10-in-addr-arpa.id
}

resource oci_dns_rrset export_0-10-in-addr-arpa_241-10-0-10-in--addr-arpa_PTR {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "241.10.0.10.in-addr.arpa"
  items {
    domain = "241.10.0.10.in-addr.arpa"
    rdata  = "host-10-0-10-241.sub0737b9ea5.cluster1.oraclevcn.com."
    rtype  = "PTR"
    ttl    = "300"
  }
  rtype = "PTR"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_0-10-in-addr-arpa.id
}

resource oci_dns_rrset export_private-testvcn-oraclevcn-com_private-testvcn-oraclevcn-com_NS {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "private.testvcn.oraclevcn.com"
  items {
    domain = "private.testvcn.oraclevcn.com"
    rdata  = "vcn-dns.oraclevcn.com."
    rtype  = "NS"
    ttl    = "86400"
  }
  rtype = "NS"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_private-testvcn-oraclevcn-com.id
}

resource oci_dns_rrset export_private-testvcn-oraclevcn-com_private-testvcn-oraclevcn-com_SOA {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "private.testvcn.oraclevcn.com"
  items {
    domain = "private.testvcn.oraclevcn.com"
    rdata  = "vcn-dns.oraclevcn.com. hostmaster.oracle.com. 9 3600 3600 3600 10"
    rtype  = "SOA"
    ttl    = "86400"
  }
  rtype = "SOA"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_private-testvcn-oraclevcn-com.id
}

resource oci_dns_rrset export_public-testvcn-oraclevcn-com_public-testvcn-oraclevcn-com_NS {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "public.testvcn.oraclevcn.com"
  items {
    domain = "public.testvcn.oraclevcn.com"
    rdata  = "vcn-dns.oraclevcn.com."
    rtype  = "NS"
    ttl    = "86400"
  }
  rtype = "NS"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_public-testvcn-oraclevcn-com.id
}

resource oci_dns_rrset export_public-testvcn-oraclevcn-com_public-testvcn-oraclevcn-com_SOA {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "public.testvcn.oraclevcn.com"
  items {
    domain = "public.testvcn.oraclevcn.com"
    rdata  = "vcn-dns.oraclevcn.com. hostmaster.oracle.com. 5 3600 3600 3600 10"
    rtype  = "SOA"
    ttl    = "86400"
  }
  rtype = "SOA"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_public-testvcn-oraclevcn-com.id
}

resource oci_dns_rrset export_0-192-in-addr-arpa_0-192-in--addr-arpa_NS {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "0.192.in-addr.arpa"
  items {
    domain = "0.192.in-addr.arpa"
    rdata  = "vcn-dns.oraclevcn.com."
    rtype  = "NS"
    ttl    = "86400"
  }
  rtype = "NS"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_0-192-in-addr-arpa.id
}

resource oci_dns_rrset export_0-192-in-addr-arpa_0-192-in--addr-arpa_SOA {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "0.192.in-addr.arpa"
  items {
    domain = "0.192.in-addr.arpa"
    rdata  = "vcn-dns.oraclevcn.com. hostmaster.oracle.com. 13 3600 3600 3600 10"
    rtype  = "SOA"
    ttl    = "86400"
  }
  rtype = "SOA"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_0-192-in-addr-arpa.id
}

